# Code Borrowed from Fabisa.is and Svavar Konradarspns Fab Academy Site.
# Fabisa: https://github.com/fablabisastaff/fabisa_site/blob/main/mkdocs.yml
# Svavar: https://gitlab.fabcloud.org/academany/fabacademy/2023/labs/isafjordur/students/svavar-konradsson/-/blob/main/mkdocs.yml?ref_type=heads

site_name: Evert´s Fab Academy Journey 
site_url: https://cptstebbi.github.io/fabtest

repo_url: https://github.com/cptstebbi/fabtest
repo_name: "Site Repo"
theme:
  name: material
  logo: images/Logo/FabLabLogo.svg
  favicon: images/Logo/FabLabLogo.svg
  icon:
    repo: simple/github
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"  # Toggle for light mode
      scheme: default
      toggle: 
        icon: material/lightbulb
        name: Switch to dark mode
      primary: pink
      accent: red
    - media: "(prefers-color-scheme: dark)"   # Toggle for dark mode
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: green 
      accent: yellow 
  font:
    text: Roboto 
    code: Roboto Mono  

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true


nav:
  - Home: index.md
  - About:
    - Bio: About/bio.md
  - Assignments:
    - 1. Webpage: Assignment/week1.md
    - 2. Electronic circut: Assignment/week2.md
    - 3. Computer-aided design: Assignment/week3.md
    - 4. Computer-controlled cutting: Assignment/week4.md
    - 5. Electronics production: Assignment/week5.md
    - 6. Week 6: Assignment/week6.md
    - 7. Week 7: Assignment/week7.md
    - 8. Week 8: Assignment/week8.md
    - 9. Week 9: Assignment/week9.md
    - 10. Week 10: Assignment/week10.md
    - 11. Week 11: Assignment/week11.md
    - 12. Week 12: Assignment/week12.md
    - 13 Week 13: Assignment/week13.md
    - 14. Week 14: Assignment/week14.md
    - 15. Week 15: Assignment/week15.md
    - 16. Week 16: Assignment/week16.md
    - 17. Week 17: Assignment/week17.md
    - 18. Week 18: Assignment/week18.md
    - 19. Week 19: Assignment/week19.md
    - 20. Week 20: Assignment/week20.md
    - 21. Final Project: Assignment/finalproject.md
    - 22.  test: Assignment/newtest1.md
    
  - Prefab: 
    - Prefabs: Prefab/Pre_fabs.md
    - Website: Prefab/Website.md


    

