# Code Borrowed from Fabisa.is and Svavar Konradarspns Fab Academy Site.
# Fabisa: https://github.com/fablabisastaff/fabisa_site/blob/main/mkdocs.yml
# Svavar: https://gitlab.fabcloud.org/academany/fabacademy/2023/labs/isafjordur/students/svavar-konradsson/-/blob/main/mkdocs.yml?ref_type=heads

site_name: Evert´s Fab Academy Journey 
site_url: https://bjarturleohlynsson.github.io/fab-academy-test-site/

repo_url: https://github.com/Cptstebbi/fabtest
repo_name: "Site Repo"
theme:
  name: material
  logo: images/Logo/FabLabLogo.svg
  favicon: images/Logo/FabLabLogo.svg
  icon:
    repo: simple/github
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"  # Toggle for light mode
      scheme: default
      toggle: 
        icon: material/lightbulb
        name: Switch to dark mode
      primary: black
      accent: red
    - media: "(prefers-color-scheme: dark)"   # Toggle for dark mode
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: green 
      accent: yellow 
  font:
    text: Roboto 
    code: Roboto Mono  

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true



